# NXEngine sources for G&W
NXENGINE_CXX_SOURCES := \
third_party/nxengine/ObjManager.cpp \
third_party/nxengine/TextBox/ItemImage.cpp \
third_party/nxengine/TextBox/SaveSelect.cpp \
third_party/nxengine/TextBox/StageSelect.cpp \
third_party/nxengine/TextBox/TextBox.cpp \
third_party/nxengine/TextBox/YesNoPrompt.cpp \
third_party/nxengine/ai/IrregularBBox.cpp \
third_party/nxengine/ai/ai.cpp \
third_party/nxengine/ai/almond/almond.cpp \
third_party/nxengine/ai/balrog_common.cpp \
third_party/nxengine/ai/boss/balfrog.cpp \
third_party/nxengine/ai/boss/ballos.cpp \
third_party/nxengine/ai/boss/core.cpp \
third_party/nxengine/ai/boss/heavypress.cpp \
third_party/nxengine/ai/boss/ironhead.cpp \
third_party/nxengine/ai/boss/omega.cpp \
third_party/nxengine/ai/boss/sisters.cpp \
third_party/nxengine/ai/boss/undead_core.cpp \
third_party/nxengine/ai/boss/x.cpp \
third_party/nxengine/ai/egg/egg.cpp \
third_party/nxengine/ai/egg/egg2.cpp \
third_party/nxengine/ai/egg/igor.cpp \
third_party/nxengine/ai/final_battle/balcony.cpp \
third_party/nxengine/ai/final_battle/doctor.cpp \
third_party/nxengine/ai/final_battle/doctor_common.cpp \
third_party/nxengine/ai/final_battle/doctor_frenzied.cpp \
third_party/nxengine/ai/final_battle/final_misc.cpp \
third_party/nxengine/ai/final_battle/misery_battle.cpp \
third_party/nxengine/ai/final_battle/sidekicks.cpp \
third_party/nxengine/ai/first_cave/first_cave.cpp \
third_party/nxengine/ai/hell/ballos_misc.cpp \
third_party/nxengine/ai/hell/ballos_priest.cpp \
third_party/nxengine/ai/hell/hell.cpp \
third_party/nxengine/ai/last_cave/last_cave.cpp \
third_party/nxengine/ai/maze/balrog_boss_missiles.cpp \
third_party/nxengine/ai/maze/critter_purple.cpp \
third_party/nxengine/ai/maze/gaudi.cpp \
third_party/nxengine/ai/maze/labyrinth_m.cpp \
third_party/nxengine/ai/maze/maze.cpp \
third_party/nxengine/ai/maze/pooh_black.cpp \
third_party/nxengine/ai/npc/balrog.cpp \
third_party/nxengine/ai/npc/curly.cpp \
third_party/nxengine/ai/npc/curly_ai.cpp \
third_party/nxengine/ai/npc/misery_ai.cpp \
third_party/nxengine/ai/npc/npcguest.cpp \
third_party/nxengine/ai/npc/npcplayer.cpp \
third_party/nxengine/ai/npc/npcregu.cpp \
third_party/nxengine/ai/oside/oside.cpp \
third_party/nxengine/ai/plantation/plantation.cpp \
third_party/nxengine/ai/sand/curly_boss.cpp \
third_party/nxengine/ai/sand/puppy.cpp \
third_party/nxengine/ai/sand/sand.cpp \
third_party/nxengine/ai/sand/toroko_frenzied.cpp \
third_party/nxengine/ai/sym/smoke.cpp \
third_party/nxengine/ai/sym/sym.cpp \
third_party/nxengine/ai/village/balrog_boss_running.cpp \
third_party/nxengine/ai/village/ma_pignon.cpp \
third_party/nxengine/ai/village/village.cpp \
third_party/nxengine/ai/weapons/blade.cpp \
third_party/nxengine/ai/weapons/bubbler.cpp \
third_party/nxengine/ai/weapons/fireball.cpp \
third_party/nxengine/ai/weapons/missile.cpp \
third_party/nxengine/ai/weapons/nemesis.cpp \
third_party/nxengine/ai/weapons/polar_mgun.cpp \
third_party/nxengine/ai/weapons/snake.cpp \
third_party/nxengine/ai/weapons/spur.cpp \
third_party/nxengine/ai/weapons/weapons.cpp \
third_party/nxengine/ai/weapons/whimstar.cpp \
third_party/nxengine/ai/weed/balrog_boss_flying.cpp \
third_party/nxengine/ai/weed/frenzied_mimiga.cpp \
third_party/nxengine/ai/weed/weed.cpp \
third_party/nxengine/autogen/AssignSprites.cpp \
third_party/nxengine/autogen/objnames.cpp \
third_party/nxengine/caret.cpp \
third_party/nxengine/common/BList.cpp \
third_party/nxengine/common/DBuffer.cpp \
third_party/nxengine/common/DString.cpp \
third_party/nxengine/common/FileBuffer.cpp \
third_party/nxengine/common/InitList.cpp \
third_party/nxengine/common/StringList.cpp \
third_party/nxengine/common/bufio.cpp \
third_party/nxengine/common/misc_comm.cpp \
third_party/nxengine/common/stat.cpp \
third_party/nxengine/console.cpp \
third_party/nxengine/debug.cpp \
third_party/nxengine/endgame/CredReader.cpp \
third_party/nxengine/endgame/credits.cpp \
third_party/nxengine/endgame/island.cpp \
third_party/nxengine/endgame/misc_end.cpp \
third_party/nxengine/floattext.cpp \
third_party/nxengine/game.cpp \
third_party/nxengine/graphics/cjkfont.cpp \
third_party/nxengine/graphics/font.cpp \
third_party/nxengine/graphics/graphics.cpp \
third_party/nxengine/graphics/nxsurface.cpp \
third_party/nxengine/graphics/palette.cpp \
third_party/nxengine/graphics/safemode.cpp \
third_party/nxengine/graphics/sprites.cpp \
third_party/nxengine/graphics/tileset.cpp \
third_party/nxengine/input.cpp \
third_party/nxengine/intro/intro.cpp \
third_party/nxengine/intro/title.cpp \
third_party/nxengine/inventory.cpp \
third_party/nxengine/main.cpp \
third_party/nxengine/map.cpp \
third_party/nxengine/map_system.cpp \
third_party/nxengine/niku.cpp \
third_party/nxengine/object.cpp \
third_party/nxengine/p_arms.cpp \
third_party/nxengine/pause/dialog.cpp \
third_party/nxengine/pause/message.cpp \
third_party/nxengine/pause/objects.cpp \
third_party/nxengine/pause/options.cpp \
third_party/nxengine/pause/pause.cpp \
third_party/nxengine/platform.cpp \
third_party/nxengine/player.cpp \
third_party/nxengine/playerstats.cpp \
third_party/nxengine/profile.cpp \
third_party/nxengine/replay.cpp \
third_party/nxengine/screeneffect.cpp \
third_party/nxengine/settings.cpp \
third_party/nxengine/siflib/sectSprites.cpp \
third_party/nxengine/siflib/sectStringArray.cpp \
third_party/nxengine/siflib/sif.cpp \
third_party/nxengine/siflib/sifloader.cpp \
third_party/nxengine/slope.cpp \
third_party/nxengine/sound/org.cpp \
third_party/nxengine/sound/pxt.cpp \
third_party/nxengine/sound/sound.cpp \
third_party/nxengine/sound/sslib.cpp \
third_party/nxengine/stageboss.cpp \
third_party/nxengine/stagedata.cpp \
third_party/nxengine/statusbar.cpp \
third_party/nxengine/trig.cpp \
third_party/nxengine/tsc.cpp
